name: Fetch and Upload Temurin SBOMs to DependencyTrack

on:
  workflow_dispatch:

env:
  DEPENDENCY_TRACK_URL: https://dtapi.northdepot.ca/

jobs:
  fetch-sboms:
    runs-on: ubuntu-latest

    outputs: 
      sbom-metadata: ${{ steps.export.outputs.matrix }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          pip install requests

      - name: Run SBOM fetcher script
        run: python fetch_sboms.py

      - name: Upload SBOMs and metadata
        uses: actions/upload-artifact@v4
        with:
          name: sboms
          path: |
            sboms
            metadata.json

      - id: export         
        run: |
          matrix=$(jq -c '.' metadata.json)   
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  store-each-sbom:
    needs: fetch-sboms
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include: ${{ fromJson(needs.fetch-sboms.outputs.sbom-metadata) }}

    steps:
      - name: Download SBOMs
        uses: actions/download-artifact@v4
        with:
          name: sboms
          path: workspace

      - name: Store SBOM in DependencyTrack   
        env:
          DTRACK_API_KEY: ${{ secrets.DEP_TRACK_TOKEN }}
        run: |
          echo "Storing SBOM for project: ${{ matrix.projectName }}, version: ${{ matrix.projectVersion }}, parent: ${{ matrix.parentProject }}"
          
          if [ -z "${{ matrix.parentProject }}" ]; then
            echo "Skipping upload — parentProject is missing"
            exit 0
          fi
          ls -l "workspace/${{ matrix.path }}"
          curl -X POST "$DEPENDENCY_TRACK_URL/api/v1/bom" \
            -H "X-Api-Key: $DTRACK_API_KEY" \
            -H "Content-Type: multifpart/form-data" \
            -F "projectName=${{ matrix.projectName }}" \
            -F "projectVersion=${{ matrix.projectVersion }}" \
            -F "parent=${{ matrix.parentProject }}" \
            -F "bom=@workspace/sboms${{ matrix.path }}" \
            -F "autoCreate=true"
