#querying from dependency track list of projects
name: Dependency Track


on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2


    - name: Query from DT
      env:
        DEPENDENCY_TRACK_API_KEY: ${{ secrets.DEP_TRACK_TOKEN }}
      run: |
        echo "Fetching vulnerabilities..."
        curl -s -H "X-Api-Key: $DEPENDENCY_TRACK_API_KEY" https://dtapi.northdepot.ca/api/v1/vulnerability/project/e31cecde-9ba5-45ea-816f-7d1d10fb5fe9



